### ISSUE TITLE
Prima Pagina

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/firstpage#1]
visualizza la pagina con un browser.
che differenza noti tra quello che
è stato scritto e quello che
viene visualizzato dal browser?

**Comment by Teodoro777** [comment]
L'unica differenza è che nel browser non va a capo

2016-02-09 20:45 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Esatto. Il browser ignora gli spazi che d'ora in avanti useremo solo per rendere più comprensibile a noi il codice
