### ISSUE TITLE
I tag

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/firstpage#2]

**Comment by FabioZTessitore** [comment]
## Nidificare i tag

I tag possono essere inclusi all'interno di altri tag
prestando attenzione a chiudere prima il tag interno e poi quello esterno.

Es. Il tag `em` serve a mettere in evidenza una porzione del testo
e puo' naturalmente essere utilizzato all'interno di un paragrafo.

```html
<p>Il linguaggio HTML <em>non</em> sembra difficile</p>
```

**Comment by Teodoro777** [comment]
Ok

Il giorno 9 febbraio 2016 22:01, Fabio Z Tessitore <notifications@github.com
