### ISSUE TITLE
Pagina completa

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/firstpage#3]

**Comment by Teodoro777** [comment]
Cose del genere: <html lang="it"> e <meta charset="utf-8"> le ho sempre
omesse

2016-02-09 22:04 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Male

**Comment by Teodoro777** [comment]
A funzionare funzionava tutto, ma comunque ora so a che servono

2016-02-09 22:25 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Bene, Dimmi quando ok per proseguire

**Comment by Teodoro777** [comment]
Possiamo proseguire, solo che non mettevo nemmeno il doctype

Il martedì 9 febbraio 2016, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Malissimo
